stages:
  - test
  - build

unit_test:
  image: golang:1.18-bullseye
  stage: test
  variables:
    GOARCH: amd64
  tags:
    - amd64
  script: ./release/test.sh

unit_test_arm64:
  extends: unit_test
  variables:
    GOARCH: arm64
  tags:
    - arm64

build_amd64_linux:
  image: golang:1.18-bullseye
  stage: build
  variables:
    GOARCH: amd64
    GOOS: linux
  tags:
    - amd64
  artifacts:
    paths:
      - build/amd64-linux/
  script: ./release/build.sh

build_arm64_linux:
  extends: build_amd64_linux
  stage: build
  variables:
    GOARCH: arm64
    GOOS: linux
  artifacts:
    paths:
      - build/arm64-linux/